//
//  CharacterListPresenter.swift
//  CleanSwiftTest
//
//  Created by Ruslan Liulka on 02.05.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CharacterListPresentationLogic
{
    func presentSomething(response: CharacterList.FetchCharacter.Response)
}

class CharacterListPresenter: CharacterListPresentationLogic
{
    weak var viewController: CharacterListDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: CharacterList.FetchCharacter.Response)
    {
        let rows = response.response.map { character in
            return CharacterViewModel(id: character.id, name: character.name, image: character.image)
        }
        
        let viewModel = CharacterList.FetchCharacter.ViewModel(viewModel: rows)
        viewController?.displaySomething(viewModel: viewModel)
    }
}
