//
//  CharacterListWorker.swift
//  CleanSwiftTest
//
//  Created by Ruslan Liulka on 02.05.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class CharacterListWorker
{
    
    func fetchCharacter(completion: @escaping (Result<CharacterResponse, Error>) -> Void) {
        
//        NetworkService.shared.fetchCharacter(type: CharacterResponse.self) {(result : Result<CharacterResponse, Error>) in
//            completion(result)
//        }
        
        NetworkService.shared.fetchCharacter(type: CharacterResponse.self) {result in
            completion(result)
        }

    }
 }
