//
//  CharacterListInteractor.swift
//  CleanSwiftTest
//
//  Created by Ruslan Liulka on 02.05.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CharacterListBusinessLogic
{
  func doSomething(request: CharacterList.Something.Request)
}

protocol CharacterListDataStore
{
  //var name: String { get set }
}

class CharacterListInteractor: CharacterListBusinessLogic, CharacterListDataStore
{
  var presenter: CharacterListPresentationLogic?
  var worker: CharacterListWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: CharacterList.Something.Request)
  {
    worker = CharacterListWorker()
    worker?.doSomeWork()
    
    let response = CharacterList.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
