//
//  CharacterListModels.swift
//  CleanSwiftTest
//
//  Created by Ruslan Liulka on 02.05.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit


struct CharacterViewModel {
    let id: Int
    let name: String
//    let gender: String
    let image: String
}

enum CharacterList
{
    // MARK: Use cases
    
    enum FetchCharacter
    {
        struct Request
        {
        }
        struct Response
        {
            let response: [CharacterStruct]
        }
        struct ViewModel
        {
            let viewModel: [CharacterViewModel]
        }
    }
}
