//
//  CharacterListWorker.swift
//  CleanSwiftTest
//
//  Created by Ruslan Liulka on 02.05.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class CharacterListWorker
{
//    func getMockCharacter() -> [Character]
//    {
//        return [
//            Character(id: 1, name: "One", gender: "None", image: ""),
//            Character(id: 2, name: "Two", gender: "None", image: ""),
//            Character(id: 3, name: "Three", gender: "None", image: ""),
//            Character(id: 4, name: "Four", gender: "None", image: ""),
//            Character(id: 5, name: "Five", gender: "None", image: ""),
//            Character(id: 6, name: "Six", gender: "None", image: "")
//        ]
//        
//    }
    
    func fetchCharacter(completion: @escaping (Result<CharacterResponse, Error>) -> Void) {
        NetworkService.shared.fetchCharacter { result in
            completion(result)
        }
    }
 }
