//
//  CharacterDetailsInteractor.swift
//  CleanSwiftTest
//
//  Created by Ruslan Liulka on 06.05.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CharacterDetailsBusinessLogic
{
    func doSomething(request: CharacterDetails.Character.Request)
}

protocol CharacterDetailsDataStore
{
    var characterId: Int? { get set }
}

class CharacterDetailsInteractor: CharacterDetailsBusinessLogic, CharacterDetailsDataStore
{
    var characterId: Int?
    
    var presenter: CharacterDetailsPresentationLogic?
    var worker: CharacterDetailsWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: CharacterDetails.Character.Request)
    {
        worker = CharacterDetailsWorker()
        
        print(characterId)
        guard let id = characterId else { return }
        print(id)
        worker?.fetchDetailsById(id) { result in
            switch result {
            case .success(let success):
                let response = CharacterDetails.Character.Response(response: success)
                self.presenter?.presentSomething(response: response)
            case .failure(let failure):
                print("INTERACTOR ERROR: \(failure)")
            }
        }

    }
}
