//
//  CharacterDetailsModels.swift
//  CleanSwiftTest
//
//  Created by Ruslan Liulka on 06.05.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

struct CharacterStructDetails: Codable {
    let id: Int
    let name: String
    let gender: String
    let image: String
    let species: String
    let origin: Origin
}

struct Origin: Codable {
    let name: String
    let url: String
}
struct CharacterDetailsViewModel: Codable {
    let id: Int
    let name: String
    let gender: String
    let image: String
    let species: String
    let originName: String
    let originUrl: String
}

enum CharacterDetails
{
    // MARK: Use cases
    
    enum Character
    {
        struct Request
        {
        }
        struct Response
        {
            let response: CharacterStructDetails
        }
        struct ViewModel
        {
            let viewModel: CharacterDetailsViewModel
        }
    }
}
