//
//  CharacterDetailsPresenter.swift
//  CleanSwiftTest
//
//  Created by Ruslan Liulka on 06.05.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CharacterDetailsPresentationLogic
{
  func presentSomething(response: CharacterDetails.Something.Response)
}

class CharacterDetailsPresenter: CharacterDetailsPresentationLogic
{
  weak var viewController: CharacterDetailsDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: CharacterDetails.Something.Response)
  {
    let viewModel = CharacterDetails.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
