//
//  CharacterDetailsPresenter.swift
//  CleanSwiftTest
//
//  Created by Ruslan Liulka on 06.05.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CharacterDetailsPresentationLogic
{
    func presentSomething(response: CharacterDetails.Character.Response)
}

class CharacterDetailsPresenter: CharacterDetailsPresentationLogic
{
    weak var viewController: CharacterDetailsDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: CharacterDetails.Character.Response)
    {
        
        let details = CharacterDetailsViewModel(id: response.response.id, name: response.response.name, gender: response.response.gender, image: response.response.image, species: response.response.species, originName: response.response.origin.name, originUrl: response.response.origin.url)
        
        let viewModel = CharacterDetails.Character.ViewModel(viewModel: details)
        viewController?.displaySomething(viewModel: viewModel)
    }
}
