//
//  CharacterDetailsWorker.swift
//  CleanSwiftTest
//
//  Created by Ruslan Liulka on 06.05.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class CharacterDetailsWorker
{
    func fetchDetailsById(_ id: Int, completion: @escaping (Result<CharacterStructDetails, Error>) -> Void) {
        NetworkService.shared.fetchCharacter(type: CharacterStructDetails.self, id: id) { result in
            completion(result)
        }
    }
}
