//
//  ChatalogListModels.swift
//  TestCleanSwift
//
//  Created by Ruslan Liulka on 29.04.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

struct Product {
    let id: Int
    let title: String
    let description: String
    let imageUrl: String
}

struct ViewModelProduct {
    let id: Int
    let title: String
    let description: String
    let imageUrl: String
}

enum ChatalogList
{
    // MARK: Use cases
    
    enum Chatalog
    {
        struct Request {
        }
        struct Response {
            let products: [Product]
        }
        struct ViewModel{
            let productsViewModel: [ViewModelProduct]
        }
    }
}
