//
//  ChatalogListInteractor.swift
//  TestCleanSwift
//
//  Created by Ruslan Liulka on 29.04.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChatalogListBusinessLogic
{
  func doSomething(request: ChatalogList.Something.Request)
}

protocol ChatalogListDataStore
{
  //var name: String { get set }
}

class ChatalogListInteractor: ChatalogListBusinessLogic, ChatalogListDataStore
{
  var presenter: ChatalogListPresentationLogic?
  var worker: ChatalogListWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: ChatalogList.Something.Request)
  {
    worker = ChatalogListWorker()
    worker?.doSomeWork()
    
    let response = ChatalogList.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
