//
//  ChatalogListPresenter.swift
//  TestCleanSwift
//
//  Created by Ruslan Liulka on 29.04.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChatalogListPresentationLogic
{
  func presentSomething(response: ChatalogList.Something.Response)
}

class ChatalogListPresenter: ChatalogListPresentationLogic
{
  weak var viewController: ChatalogListDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: ChatalogList.Something.Response)
  {
    let viewModel = ChatalogList.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
