//
//  CatalogListInteractor.swift
//  TestCleanSwift
//
//  Created by Ruslan Liulka on 29.04.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CatalogListBusinessLogic
{
    func doCatalog(request: CharacterList.FetchCharacter.Request)
}

protocol CatalogListDataStore
{
    //var name: String { get set }
}

class CatalogListInteractor: CatalogListBusinessLogic, CatalogListDataStore
{
    var presenter: CatalogListPresentationLogic?
    var worker: CatalogListWorker?
    //var name: String = ""
    
    // MARK: Do Catalog
    
    func doCatalog(request: CharacterList.FetchCharacter.Request)
    {
        worker = CatalogListWorker()
        //        let products = worker?.getSomeCatalog() ?? []
        //
        //        let response = CatalogList.Catalog.Response(products: products)
        //        self.presenter?.presentCatalog(response: response)
        
        worker?.fetchData { result in
            switch result {
            case .success(let success):
                let response = CharacterList.FetchCharacter.Response(characters: success.results)
                self.presenter?.presentCatalog(response: response)
            case .failure(let failure):
                print("FAILURE INTERACTOR")
            }
        }
        
    }
}
