//
//  CatalogListWorker.swift
//  TestCleanSwift
//
//  Created by Ruslan Liulka on 29.04.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class CatalogListWorker
{
    func getSomeCatalog() -> [Product]{
        return [
            Product(id: 1, title: "Chair", description: "Good Chair", imageUrl: ""),
            Product(id: 2, title: "Pants", description: "Good Pants", imageUrl: ""),
            Product(id: 3, title: "Food", description: "Good Food", imageUrl: ""),
            Product(id: 4, title: "Mock Shirt", description: "Comfortable cotton shirt", imageUrl: ""),
            Product(id: 5, title: "Mock Shoes", description: "Stylish sneakers", imageUrl: "")
        ]
    }
}
