//
//  ChatalogListViewController.swift
//  TestCleanSwift
//
//  Created by Ruslan Liulka on 29.04.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChatalogListDisplayLogic: class
{
    func displayChatalog(viewModel: ChatalogList.Chatalog.ViewModel)
}

class ChatalogListViewController: UIViewController, ChatalogListDisplayLogic
{
    var interactor: ChatalogListBusinessLogic?
    var router: (NSObjectProtocol & ChatalogListRoutingLogic & ChatalogListDataPassing)?
    
    private let tableView = UITableView()
    private var products: [ViewModelProduct] = []
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    private func setupTableView() {
        tableView.frame = view.bounds
        tableView.autoresizingMask = [.flexibleWidth, .flexibleHeight]
        tableView.delegate = self
        tableView.dataSource = self
        tableView.register(UITableViewCell.self, forCellReuseIdentifier: "Cell")
        view.addSubview(tableView)
    }
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = ChatalogListInteractor()
        let presenter = ChatalogListPresenter()
        let router = ChatalogListRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        setupTableView()
        doChatalog()
    }
    
    // MARK: Do Chatalog
    
    //@IBOutlet weak var nameTextField: UITextField!
    
    func doChatalog()
    {
        let request = ChatalogList.Chatalog.Request()
        interactor?.doChatalog(request: request)
    }
    
    func displayChatalog(viewModel: ChatalogList.Chatalog.ViewModel)
    {
        products = viewModel.productsViewModel
        tableView.reloadData()
    }
}

extension ChatalogListViewController: UITableViewDataSource {
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        print(products.count)
        return products.count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "Cell", for: indexPath)
        
        cell.textLabel?.text = products[indexPath.row].title
        return cell
    }
    
    
}

extension ChatalogListViewController: UITableViewDelegate {
    
}
