//
//  CatalogListModels.swift
//  TestCleanSwift
//
//  Created by Ruslan Liulka on 29.04.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

//struct Product {
//    let id: Int
//    let title: String
//    let description: String
//    let imageUrl: String
//}
//
//struct ViewModelProduct {
//    let id: Int
//    let title: String
//    let description: String
//    let imageUrl: String
//}
//
//enum CatalogList
//{
//    // MARK: Use cases
//    
//    enum Catalog
//    {
//        struct Request {
//        }
//        struct Response {
//            let products: [Product]
//        }
//        struct ViewModel{
//            let productsViewModel: [ViewModelProduct]
//        }
//    }
//}


enum CharacterList
{
    // MARK: Use cases
    //    struct Character {
    //        let name: String
    //    }
    
    struct CharacterDisplay {
        let id: Int
        let name: String
        let status: String
        let species: String
        let gender: String
        let imageURL: String
    }
    
    
    
    enum FetchCharacter {
        struct Request {
            var urlString: String?
        }
        struct Response {
            let characters: [Character]
        }
        struct ViewModel {
            let displayCharacter: [CharacterDisplay]
        }
    }
}

