//
//  CatalogListPresenter.swift
//  TestCleanSwift
//
//  Created by Ruslan Liulka on 29.04.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CatalogListPresentationLogic
{
    func presentCatalog(response: CatalogList.Catalog.Response)
}

class CatalogListPresenter: CatalogListPresentationLogic
{
    weak var viewController: CatalogListDisplayLogic?
    
    // MARK: Do Catalog
    
    func presentCatalog(response: CatalogList.Catalog.Response)
    {
        
        let rows = response.products.map { product in
            return ViewModelProduct(id: product.id, title: product.title, description: product.description, imageUrl: product.imageUrl)
        }
        
        let viewModel = CatalogList.Catalog.ViewModel(productsViewModel: rows)
        viewController?.displayCatalog(viewModel: viewModel)
    }
}
